workflows:
  vogue-cars-workflow:
    name: Vogue Cars Final Build
    instance_type: mac_mini_m1
    max_build_duration: 30

    environment:
      flutter: 3.24.0
      java: 17
      vars:
        CACHE_INVALIDATOR: 2

    scripts:
      # --------------------------------------------------
      # 1) Force & Verify Java 17 (macOS runner safe)
      # --------------------------------------------------
      - name: Verify & Fix Java (JDK 17)
        script: |
          echo "Before fix:"
          which java || true
          java -version || true
          echo "JAVA_HOME(before)=$JAVA_HOME"

          export JAVA_HOME=$(/usr/libexec/java_home -v 17)
          export PATH="$JAVA_HOME/bin:$PATH"

          echo "After fix:"
          echo "JAVA_HOME(after)=$JAVA_HOME"
          which java
          java -version
          flutter --version

      # --------------------------------------------------
      # 2) Remove any old Flutter v1 generated Java
      #    (hard stop for GeneratedPluginRegistrant errors)
      # --------------------------------------------------
      - name: Remove old Flutter v1 generated files
        script: |
          rm -rf android/app/src/main/java/io/flutter

      # --------------------------------------------------
      # 3) Full clean (Flutter + Gradle) to avoid stale cache
      # --------------------------------------------------
      - name: Full Clean (Flutter + Gradle)
        script: |
          flutter clean

          # Clear Gradle caches/daemon once to avoid old configs
          rm -rf ~/.gradle/caches
          rm -rf ~/.gradle/daemon

          flutter pub get

          chmod +x android/gradlew
          cd android
          ./gradlew clean --no-daemon
          cd ..

      # --------------------------------------------------
      # 4) Build Android App Bundle (Release)
      # --------------------------------------------------
      - name: Build App Bundle
        script: |
          flutter build appbundle --release --no-tree-shake-icons

    artifacts:
      - build/app/outputs/bundle/release/*.aab
