workflows:
  vogue-cars-workflow:
    name: Vogue Cars Release
    instance_type: mac_mini_m1
    environment:
      flutter: 3.24.0
      java: 17
    scripts:
      - name: Build App Bundle
        script: | 
          flutter clean
          flutter pub get
          flutter build appbundle --release --no-sound-null-safety
    artifacts:
      - build/app/outputs/bundle/release/*.aab
