workflows:
  vogue-cars-workflow:
    name: Vogue Cars Final Build
    instance_type: mac_mini_m1
    max_build_duration: 30

    environment:
      flutter: 3.24.0
      java: 17
      vars:
        CACHE_INVALIDATOR: 2

    scripts:
      - name: Verify & Fix Java (JDK 17)
        script: |
          echo "Before fix:"
          which java || true
          java -version || true
          echo "JAVA_HOME(before)=$JAVA_HOME"

          # Force JAVA_HOME to real JDK 17 on macOS runner
          export JAVA_HOME=$(/usr/libexec/java_home -v 17)
          export PATH="$JAVA_HOME/bin:$PATH"

          echo "After fix:"
          echo "JAVA_HOME(after)=$JAVA_HOME"
          which java
          java -version
          flutter --version

      - name: Full Clean (Flutter + Gradle)
        script: |
          flutter clean

          # Clear Gradle caches to avoid stale configs (AndroidX / old generated files)
          rm -rf ~/.gradle/caches
